image: node

stages:
  - deploy

deploy_develop:
  stage: deploy
  environment:
    name: develop
    url: http://orkg01.develop.labs.tib.eu/orkg/
  variables:
    DEPLOY_HOST: orkg01.develop.labs.tib.eu
    DEPLOY_PORT: 8080
    BACKEND_URL: http://${DEPLOY_HOST}:${DEPLOY_PORT}/orkg-prototype/api/
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'which rsync || ( apt-get -y update -y && apt-get -y install rsync )'
  script:
    # Update the build configuration to match the environment
    - sed '/^REACT_APP_SERVER_URL=/d' default.env > .env
    - echo "REACT_APP_SERVER_URL=$BACKEND_URL" >> .env
    - cat .env
    # Prepare and build
    - npm install
    - npm run build
    # Deploy to web server
    - rsync -av --delete build/ orkg@${DEPLOY_HOST}:/tib/app/orkg/www/htdocs/orkg/
  only:
    - master

