version: '3.7'

services:
    frontend:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - '127.0.0.1:80:80'
        environment:
            - REACT_APP_PUBLIC_URL=/test
